const dummyList = [
  {
    name: '홍길동',
    profileImages: undefined,
    star: 4.9,
    starCount: 230,
    like: 23,
    hire: 87,
    location: '서울특별시 강남구',
    career: 10,
    timeStart: '오전 7시',
    timeEnd: '오후 11시',
  },
  {
    name: '김철수',
    profileImages: undefined,
    star: 4.7,
    starCount: 120,
    like: 15,
    hire: 54,
    location: '경기도 성남시',
    career: 7,
    timeStart: '오전 9시',
    timeEnd: '오후 10시',
  },
  {
    name: '이영희',
    profileImages: undefined,
    star: 5.0,
    starCount: 310,
    like: 40,
    hire: 120,
    location: '부산광역시 해운대구',
    career: 12,
    timeStart: '오전 8시',
    timeEnd: '오후 9시',
  },
  {
    name: '박민수',
    profileImages: undefined,
    star: 4.8,
    starCount: 180,
    like: 32,
    hire: 70,
    location: '대전광역시 유성구',
    career: 8,
    timeStart: '오전 10시',
    timeEnd: '오후 8시',
  },
  {
    name: '최지은',
    profileImages: undefined,
    star: 4.6,
    starCount: 90,
    like: 12,
    hire: 40,
    location: '광주광역시 북구',
    career: 5,
    timeStart: '오전 8시',
    timeEnd: '오후 7시',
  },
  {
    name: '정우성',
    profileImages: undefined,
    star: 4.95,
    starCount: 400,
    like: 55,
    hire: 200,
    location: '인천광역시 연수구',
    career: 15,
    timeStart: '오전 6시',
    timeEnd: '오후 10시',
  },
  {
    name: '정우성',
    profileImages: undefined,
    star: 4.95,
    starCount: 400,
    like: 55,
    hire: 200,
    location: '인천광역시 연수구',
    career: 15,
    timeStart: '오전 6시',
    timeEnd: '오후 10시',
  },
  {
    name: '정우성',
    profileImages: undefined,
    star: 4.95,
    starCount: 400,
    like: 55,
    hire: 200,
    location: '인천광역시 연수구',
    career: 15,
    timeStart: '오전 6시',
    timeEnd: '오후 10시',
  },
];

export default dummyList;
