const dummyExpertBasicInfoList = [
  {
    message: '조회에 성공했습니다.',
    data: {
      list:[
         {
          nickName: '홍길동',
          profileImg: undefined,
          starScore: 4.9,
          reviewCount: 230,
          totalLike: 23,
          completedJobs: 87,
          address: '서울특별시 강남구',
          career: 10,
          startTime: '오전 7시',
          endTime: '오후 11시',
        },
        {
          nickName: '김철수',
          profileImg: undefined,
          starScore: 4.7,
          reviewCount: 120,
          totalLike: 15,
          completedJobs: 54,
          address: '경기도 성남시',
          career: 7,
          startTime: '오전 9시',
          endTime: '오후 10시',
        },
        {
          nickName: '이영희',
          profileImg: undefined,
          starScore: 5.0,
          reviewCount: 310,
          totalLike: 40,
          completedJobs: 120,
          address: '부산광역시 해운대구',
          career: 12,
          startTime: '오전 8시',
          endTime: '오후 9시',
        },
        {
          nickName: '박민수',
          profileImg: undefined,
          starScore: 4.8,
          reviewCount: 180,
          totalLike: 32,
          completedJobs: 70,
          address: '대전광역시 유성구',
          career: 8,
          startTime: '오전 10시',
          endTime: '오후 8시',
        },
        {
          nickName: '최지은',
          profileImg: undefined,
          starScore: 4.6,
          reviewCount: 90,
          totalLike: 12,
          completedJobs: 40,
          address: '광주광역시 북구',
          career: 5,
          startTime: '오전 8시',
          endTime: '오후 7시',
        },
        {
          nickName: '정우성',
          profileImg: undefined,
          starScore: 4.95,
          reviewCount: 400,
          totalLike: 55,
          completedJobs: 200,
          address: '인천광역시 연수구',
          career: 15,
          startTime: '오전 6시',
          endTime: '오후 10시',
        },
        {
          nickName: '정우성',
          profileImg: undefined,
          starScore: 4.95,
          reviewCount: 400,
          totalLike: 55,
          completedJobs: 200,
          address: '인천광역시 연수구',
          career: 15,
          startTime: '오전 6시',
          endTime: '오후 10시',
        },
        {
          nickName: '정우성',
          profileImg: undefined,
          starScore: 4.95,
          reviewCount: 400,
          totalLike: 55,
          completedJobs: 200,
          address: '인천광역시 연수구',
          career: 15,
          startTime: '오전 6시',
          endTime: '오후 10시',
        },
      ]
    },
    pageInfo: {
      listCount: 3,
      currentPage:1,
      boardList:6,
      maxPage: 1,
      startPage:1,
      endPage:1,
    },
    success: true,
    timestamp: '2023-10-01T12:00:00Z',
  }
];

export default dummyExpertBasicInfoList;
